### PR TITLE
Add support for IPv6-only domains

### PR DESCRIPTION
**Pull request by cbruegg**
This solves the 'ValueError' issue when verifying domains with IPv6-only DNS records.

### CODE REVIEW

**Comment by Yannik** [comment]
Hey, is this compatible with both ipv4-only and ipv6-only domains? On the first glance it looks like this would be incompatible with ipv4-only.

**Comment by Yannik** [comment]
Apart from that, I would really like to merge your commit :-)

**Comment by cbruegg** [comment]
Whoops, looks like accidentally left an IPv4 server on during testing and wrongly concluded this change would not break IPv4. Sorry! I've added a commit that integrates IPv4 support.

**Comment by cbruegg** [comment]
Any update on this? :)

**Comment by Yannik** [comment]
Sorry for the delay. I have merged this now. :)

**Pull request merged**
