### PR TITLE
Added parameters for testing purposes and local constants for easier customization

### PR DESCRIPTION
**Pull request by T-I-K**
Included beautification: uniform logging and indentation

### CODE REVIEW

**Comment by Yannik** [comment]
I'm fine with most changes, except for the variable extraction. I don't see any compelling reasons to use any other port than port 80, or to use another private key location.

If you exclude those changes I will gladly merge this.

**Comment by aetasoul** [comment]
Hi @Yannik 
In my case use another port is required, I have one single IP with 5 NAS, actually I have to manage the redirection dinamically based on which one need to renew the certificate, with the option for custom port I can renew them without the dinamic redirect

**Comment by Yannik** [comment]
@aetasoul Also, every port forwarding config I have ever seen allows you to set src port (WAN side) and dst port (NAS side)...

**Comment by T-I-K** [comment]
@Yannik
My intention for introducing this minimal set of variables:
**RENEWAL_HTTP_PORT**
I don't trust the QNAP software with respect to security and reliability and I don't want that the NAS is responding on port 80 all the time. So I've setup a static port forwarding rule to an unused port on the QNAP. Here only the Python HTTP server is responding during acme challenge.
**PRIVATE_DOMAIN_KEY**
I don't want that private keys are part of my "generic" backup on QNAP. That's why a can configure a common place for keys without fiddling around with exception rules in the backup.

In general it's a good practice in software development to introduce local constants for repeating constant literals. It has a major (positive) impact on maintainability. But at the end you are the maintainer and you have to decide...

Just a comment related to the acme challenge an port 80:
From the internet point of view every private network is a black box. The IT administrators are responsible for security here. From the black box perspective, the acme challenge happens on port 80.
I don't see any violation here.

Of course, I can remove the offensive comment in the script so as not to encourage people to do so.

**Comment by Yannik** [comment]
@T-I-K did you forget removing the port variable from HTTPServer.py?

**Comment by T-I-K** [comment]
It was not mentioned in the review and of course it doesn't hurt. Furthermore I'll keep these changes locally here.
Is it necessary to revert these changes for you?

**Comment by Yannik** [comment]
> It was not mentioned in the review and of course it doesn't hurt. Furthermore I'll keep these changes locally here. Is it necessary to revert these changes for you?
Yes, I dont think it makes sense to keep this without using it.

**Comment by T-I-K** [comment]
Ok, done.

**Comment by T-I-K** [comment]
Please can you merge the pull request! I'm going to remove the fork as I don't like intermediate forks that fly around the world.

**Pull request closed without merging**
